import { useEffect, useState } from 'react'
import { Modal, Form, Button, Alert } from 'react-bootstrap'
import { postFolioItem } from '../services/fds/stayService'
import { useAuth } from '../context/AuthContext'

/**
 * Guest-facing version of the folio charge dialog.
 *
 * Guests must not be able to price their own charges, so unlike the staff AddChargeModal there
 * is no amount field and no charge-type dropdown: they pick a service from this fixed list and
 * the price comes from here. ROOMRENT, FBCHARGE, TAX and DISCOUNT are deliberately absent —
 * those are posted by staff or generated by the system (F&B orders post their own FBCHARGE).
 */
const SERVICES = [
  { key: 'LAUNDRY_BASIC', chargeType: 'LAUNDRY', label: 'Laundry — wash & fold', amount: 300 },
  { key: 'SPA_MASSAGE', chargeType: 'SPA', label: 'Spa — massage session', amount: 1500 },
]

export default function RequestServiceModal({ show, stayId, onClose, onSaved }) {
  const { user } = useAuth()
  const [serviceKey, setServiceKey] = useState(SERVICES[0].key)
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)

  // Reset to a clean state each time the dialog opens.
  useEffect(() => {
    if (!show) return
    setError('')
    setServiceKey(SERVICES[0].key)
  }, [show])

  const service = SERVICES.find(s => s.key === serviceKey) || SERVICES[0]

  const submit = async (e) => {
    e.preventDefault(); setSaving(true); setError('')
    try {
      await postFolioItem(stayId, {
        chargeType: service.chargeType,
        description: service.label,
        amount: service.amount,
        postedBy: user?.userId || null,
      })
      onSaved()
    } catch (err) { setError(err.message) } finally { setSaving(false) }
  }

  return (
    <Modal show={show} onHide={onClose}>
      <Modal.Header closeButton><Modal.Title>Request a Service</Modal.Title></Modal.Header>
      <Form onSubmit={submit}>
        <Modal.Body>
          {error && <Alert variant="danger" className="py-2">{error}</Alert>}
          <Form.Group className="mb-3">
            <Form.Label>Service</Form.Label>
            <Form.Select value={serviceKey} onChange={e => setServiceKey(e.target.value)}>
              {SERVICES.map(s => <option key={s.key} value={s.key}>{s.label} — ₹{s.amount}</option>)}
            </Form.Select>
          </Form.Group>
          <div className="d-flex justify-content-between border-top pt-2">
            <strong>Charged to your room</strong>
            <strong>₹{service.amount}</strong>
          </div>
          <p className="small text-muted mt-2 mb-0">
            This will be added to your bill at the listed price.
          </p>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={onClose}>Cancel</Button>
          <Button type="submit" disabled={saving}>
            {saving ? 'Requesting…' : 'Confirm Request'}
          </Button>
        </Modal.Footer>
      </Form>
    </Modal>
  )
}
